name: DOG_EMOTION
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - black=24.10.0
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cpython=3.9.21
  - cuda-cccl=12.8.90
  - cuda-cccl_linux-64=12.8.90
  - cuda-crt-dev_linux-64=12.8.61
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-dev_linux-64=12.8.90
  - cuda-cudart-static=12.8.90
  - cuda-cudart-static_linux-64=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-cuobjdump=12.8.90
  - cuda-cupti=12.4.127
  - cuda-driver-dev_linux-64=12.8.90
  - cuda-libraries=12.4.1
  - cuda-nvcc=12.8.61
  - cuda-nvcc-dev_linux-64=12.8.61
  - cuda-nvcc-impl=12.8.61
  - cuda-nvcc-tools=12.8.61
  - cuda-nvcc_linux-64=12.8.61
  - cuda-nvdisasm=12.8.90
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-dev_linux-64=12.8.61
  - cuda-nvvm-impl=12.8.61
  - cuda-nvvm-tools=12.8.61
  - cuda-opencl=12.8.90
  - cuda-runtime=12.4.1
  - cuda-version=12.8
  - cudnn=9.2.1.18
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.18
  - debugpy=1.8.13
  - decorator=5.2.1
  - deprecated=1.2.13
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.2
  - fonttools=4.56.0
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h2=4.2.0
  - hpack=4.1.0
  - huggingface_hub=0.29.3
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.7
  - imageio=2.37.0
  - importlib-metadata=8.5.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kaggle=1.6.17
  - kagglehub=0.3.8
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.13.1.3
  - libcups=2.3.3
  - libcurand=10.3.9.90
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libcxx=14.0.6
  - libcxxabi=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=3.0.0
  - libgfortran-ng=11.3.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libmlir19=19.1.7
  - libnghttp2=1.58.0
  - libnpp=12.2.5.30
  - libntlm=1.8
  - libnvfatbin=12.8.90
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsanitizer=13.3.0
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.41
  - libzlib=1.2.13
  - lit=20.1.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - magma=2.8.0
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.0.7
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - nccl=2.26.2.1
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.2.1
  - nomkl=3.0
  - nspr=4.36
  - nss=3.100
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openblas=0.3.21
  - opencl-headers=2024.10.24
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.5
  - openssl=3.4.1
  - opentelemetry-api=1.30.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pathspec=0.10.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.3
  - readline=8.2
  - requests=2.32.3
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.12.0
  - setuptools=75.8.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - timm=1.0.15
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - unidecode=1.3.8
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - wrapt=1.17.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.43
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - sympy==1.13.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - triton==3.2.0
